name: Build Debian packages

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-debian-stable:
    runs-on: ubuntu-latest
    container: debian:stable

    steps:
      - run: |
          apt-get -y update
          apt-get -y upgrade
          apt-get -y install git

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - run: |
          apt-get -y install build-essential wget
          for n in amd64:64 arm64:arm64 armhf:arm; do
            arch=`echo $n | cut -d: -f1`
            type=`echo $n | cut -d: -f2`
            echo Downloading CEF source for $arch
            mkdir $arch
            url=https://cef-builds.spotifycdn.com/cef_binary_131.4.1%2Bg437feba%2Bchromium-131.0.6778.265_linux${type}_minimal.tar.bz2
            wget -qO- $url | bunzip2 | tar -xf- -C $arch --strip-components=1
          done
          apt-get -y build-dep .
          dpkg-buildpackage --build=binary --no-sign

      - uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: ../*.deb
          overwrite: true
